name: braintree_flutter_plus_example
description: Demonstrates how to use the braintree_flutter_plus plugin.
version: 0.6.0
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.5.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  braintree_flutter_plus:
    path: ../

flutter:
  uses-material-design: true
