name: braintree_flutter_plus
description: Enhanced Flutter plugin that wraps the native Braintree SDKs with latest updates. Supports iOS 15+, Android 12+, and includes PayPal vault flow fixes.
version: 5.0.9
homepage: https://github.com/adlyyy4/flutter-braintree
repository: https://github.com/adlyyy4/flutter-braintree
issue_tracker: https://github.com/adlyyy4/flutter-braintree/issues

environment:
  sdk: ^3.8.1
  flutter: ">=2.5.0"


dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0

flutter:
  assets:
    - assets/images/

  plugin:
    platforms:
      android:
        package: com.example.flutter_braintree
        pluginClass: FlutterBraintreePlugin
      ios:
        pluginClass: FlutterBraintreePlugin
